### ISSUE TITLE
Error working with type "double"

### ISSUE THREAD

**Issue by Yaisis** [deviator/sdlss#5]
Saves the value "150,430908203125D" to the file
When reading a value from a file, it gives an error:
"Error: Unexpected comma: SDLang is not a comma-separated format."

The error occurs because when saving instead of "." the symbol "," is used

**Comment by deviator** [comment]
I think this is not the error. Floating point literals use `.` as separator in many languages and all programming languages. Form with `,` valid only for local region formats (Russian for example).

This library builds on top of [`sdlang-d`](https://github.com/Abscissa/SDLang-D). Full work of parsing input data contains in `sdlang-d` and it don't worried about local region format (like many other products).

Use `.` as separator, it's standard.

See:
https://github.com/Abscissa/SDLang-D/blob/master/src/sdlang/lexer.d#L440
https://github.com/Abscissa/SDLang-D/blob/master/src/sdlang/token.d#L254

**Comment by Yaisis** [comment]
I also think that this is the problem of the Russian layout.
It turns out that depending on external conditions, the library may work correctly or not.
This is the wrong library operation, as her work should not depend on external factors
